// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr25p5ykwf0nbM_QnMlaYQD6bUGIKe1Po',
    appId: '1:669074661675:web:2acd4de63021eece14e56e',
    messagingSenderId: '669074661675',
    projectId: 'jeff-test-7cc0a',
    authDomain: 'jeff-test-7cc0a.firebaseapp.com',
    storageBucket: 'jeff-test-7cc0a.appspot.com',
    measurementId: 'G-H52ML6NRW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ-R_yQ9UENb3xAz-qm8MQ3ZoGzmYH8lM',
    appId: '1:669074661675:android:376a86c2a72a930314e56e',
    messagingSenderId: '669074661675',
    projectId: 'jeff-test-7cc0a',
    storageBucket: 'jeff-test-7cc0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy55alMCJvxnGDPk89m53HQM8aMZ0Esqw',
    appId: '1:669074661675:ios:a7f4f650146ffa3214e56e',
    messagingSenderId: '669074661675',
    projectId: 'jeff-test-7cc0a',
    storageBucket: 'jeff-test-7cc0a.appspot.com',
    iosClientId: '669074661675-5hn92mouqf2elm6cutq9q4qf5oqj9qd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterJeffreyDev',
  );
}
